# Generated by Django 4.2.9 on 2024-02-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='products.product'),
        ),
    ]
