# Generated by Django 4.2.9 on 2024-02-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_article_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_sold',
            field=models.BooleanField(default=True),
        ),
    ]
