# Generated by Django 4.2.9 on 2024-02-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_article_product_alter_variant_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
