# Generated by Django 4.2.9 on 2024-02-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
        ('products', '0013_alter_article_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_pictures',
            field=models.ManyToManyField(blank=True, default=None, related_name='article_picture', to='pictures.pictures'),
        ),
        migrations.AddField(
            model_name='article',
            name='banner_picture',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='pictures.pictures'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='variant_pictures',
            field=models.ManyToManyField(blank=True, default=None, to='pictures.pictures'),
        ),
    ]
