# Generated by Django 4.2.9 on 2024-02-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_article_article_pictures_article_banner_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='banner_picture',
        ),
    ]
