# Generated by Django 4.2.9 on 2024-02-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_author',
        ),
        migrations.RemoveField(
            model_name='client',
            name='modified_date',
        ),
    ]
