# Generated by Django 4.2.9 on 2024-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_created_date_remove_client_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='localization',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
